In [3]:
import pandas as pd
import numpy as np
import chardet

In [24]:
with open("../final_paper_data/b01-1-1.csv","rb") as f:
    data = f.read()
    result = chardet.detect(data)
result

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

In [14]:
read_file = pd.read_excel (r"../final_paper_data/b01-1-1.xlsx")
read_file.to_csv (r"../final_paper_data/b01-1-1.csv", index = None, header=True)

In [25]:
dat1 = pd.read_csv('../final_paper_data/b01-1-1.csv',encoding='ascii')
dat1.head(15)

,Unnamed: 0,Jan.,Feb.,Mar.,Apr.,May,June,July,Aug.,Sep.,...,June.1,July.1,Aug..1,Sep..1,Oct..1,Nov..1,Dec..1,C.Y.Ave..1,F.Y.Ave..1,Unnamed: 31
0,1970.0,30.3,30.3,30.6,30.9,30.8,30.8,30.8,30.7,31.2,...,*,*,*,*,*,*,*,*,*,1970.0
1,1971.0,32.2,32.2,32.3,32.7,32.8,32.9,32.9,32.9,33.7,...,6.9,6.9,7,8,6.5,5.5,4.8,6.3,5.9,1971.0
2,1972.0,33.5,33.7,34.0,34.4,34.5,34.5,34.5,34.8,35.0,...,4.8,5,5.9,3.9,4.4,5.1,5.7,4.9,5.7,1972.0
3,1973.0,35.7,36.0,36.9,37.6,38.2,38.3,38.6,38.9,40.0,...,11,11.7,11.9,14.2,13.9,15.2,18.3,11.7,15.6,1973.0
4,1974.0,43.6,45.0,45.3,46.4,46.6,46.9,47.8,48.3,49.0,...,22.3,23.8,23.9,22.5,24.8,24.5,21,23.2,20.9,1974.0
5,1975.0,51.2,51.3,51.7,52.6,52.9,52.9,53.1,52.9,54.1,...,13.4,11.4,10.2,10.4,9.7,8.3,7.8,11.7,10.4,1975.0
6,1976.0,55.7,56.1,56.3,57.6,57.8,57.9,58.3,57.9,59.4,...,9.6,9.9,9.4,9.8,8.7,9.2,10.5,9.4,9.5,1976.0
7,1977.0,60.9,61.3,61.6,62.6,63.2,63.0,62.8,62.9,63.9,...,8.6,7.7,8.6,7.7,7.6,6.5,5,8.1,6.9,1977.0
8,1978.0,63.7,64.1,64.6,65.3,65.7,65.4,65.6,65.8,66.5,...,3.9,4.6,4.6,4.1,3.7,3.8,3.9,4.2,3.8,1978.0
9,1979.0,66.0,65.8,66.4,67.2,67.8,67.9,68.5,67.8,68.7,...,3.8,4.3,3.1,3.2,4.2,5,5.6,3.7,4.8,1979.0
10,1980.0,70.3,70.9,71.3,72.6,73.2,73.5,73.6,73.4,74.6,...,8.2,7.5,8.4,8.7,7.5,8,6.9,7.7,7.6,1980.0
11,1981.0,75.5,75.4,75.6,76.2,76.9,77.0,76.8,76.5,77.6,...,4.8,4.4,4.2,4,4.2,3.8,4.3,4.9,4,1981.0
12,1982.0,77.9,77.8,77.9,78.5,78.8,78.8,78.3,78.9,80.1,...,2.3,1.9,3.2,3.2,3.1,2.3,2,2.8,2.6,1982.0
13,1983.0,79.6,79.3,79.7,80.1,80.9,80.4,80.1,79.9,80.8,...,2,2.3,1.3,0.9,1.5,1.9,1.7,1.9,1.9,1983.0
14,1984.0,81.1,81.6,81.7,81.9,82.5,81.9,82.1,81.4,82.7,...,1.9,2.5,1.9,2.3,2.2,2.2,2.6,2.3,2.2,1984.0